version: "3.7"

services:
  gateway:
    hostname: gateway.default.svc.cluster.local
    image: kzmake/greeter:latest
    command: "/gateway"
    ports:
      - 8080:8080 # http
  greeter:
    hostname: greeter.default.svc.cluster.local
    image: kzmake/greeter:latest
    command: "/service"
