version: "3.7"

services:
  dev:
    image: curlimages/curl:latest
    command: "sh -c 'trap : SIGTERM SIGINT; sleep infinity & wait'"
  gateway:
    hostname: gateway.default.svc.cluster.local
    build:
      context: .
      dockerfile: Dockerfile
    command: "/gateway"
    environment:
      GATEWAY_ADDRESS: "0.0.0.0:8080"
      GATEWAY_SERVICE_ADDRESS: "greeter.default.svc.cluster.local:50051"
      GATEWAY_MTLS: "true"
    volumes:
      - ./certs:/certs
    ports:
      - 8080:8080 # http
  greeter:
    hostname: greeter.default.svc.cluster.local
    build:
      context: .
      dockerfile: Dockerfile
    command: "/service"
    environment:
      SERVICE_ADDRESS: "0.0.0.0:50051"
      SERVICE_MTLS: "true"
    volumes:
      - ./certs:/certs
    ports:
      - 50051:50051 # grpc
