apiVersion: skaffold/v2beta18
kind: Config
build:
  artifacts:
    - image: kzmake/greeter
      context: .
deploy:
  kustomize:
    paths:
      - manifests/greeter/overlays/localhost
portForward:
  - resourceType: service
    resourceName: gateway
    port: 80
    localPort: 8080
