---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  ADDRESS: "0.0.0.0:8080"
  SERVICE_ADDRESS: "greeter.default.svc.cluster.local:50051"
  MTLS: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: greeter-config
data:
  ADDRESS: "0.0.0.0:50051"
  MTLS: "true"
