---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: kzmake/greeter:latest
          command:
            - /gateway
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: gateway-config
              prefix: GATEWAY_
          resources:
            limits:
              cpu: 1m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
