---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter
spec:
  selector:
    matchLabels:
      app: greeter
  template:
    metadata:
      labels:
        app: greeter
    spec:
      containers:
        - name: greeter
          image: kzmake/greeter:latest
          command:
            - /service
          envFrom:
            - configMapRef:
                name: common-config
            - configMapRef:
                name: greeter-config
              prefix: SERVICE_
          resources:
            limits:
              cpu: 1m
              memory: 512Mi
          ports:
            - name: grpc
              containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: greeter
spec:
  type: ClusterIP
  selector:
    app: greeter
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
